name: "generate-status-card"
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: ppodds/mc-status-card@v0.1.1
        with:
          host: "ppodds.website"
          bgImage: "https://i.imgur.com/MNt59oI.pn"
